const MILLISECONDS_PER_SECOND = 1000;
const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * 60;
const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_MINUTE * 60;
const MILLISECONDS_PER_DAY = MILLISECONDS_PER_HOUR * 24;
const MILLISECONDS_PER_WEEK = MILLISECONDS_PER_DAY * 7;
const MILLISECONDS_PER_MOUNTH =  MILLISECONDS_PER_DAY * 30;
const MILLISECONDS_PER_YEAR = MILLISECONDS_PER_DAY * 365;

const SECONDS_PER_MINUTE = 60;
const SECONDS_PER_HOUR = SECONDS_PER_MINUTE * 60;
const SECONDS_PER_DAY = SECONDS_PER_HOUR * 24;
const SECONDS_PER_WEEK = SECONDS_PER_DAY * 7;
const SECONDS_PER_MOUNTH =  SECONDS_PER_DAY * 30;
const SECONDS_PER_YEAR = SECONDS_PER_DAY * 365;

export default Object.freeze({
    MILLISECONDS_PER_SECOND,
    MILLISECONDS_PER_MINUTE,
    MILLISECONDS_PER_HOUR,
    MILLISECONDS_PER_DAY,
    MILLISECONDS_PER_WEEK,
    MILLISECONDS_PER_MOUNTH,
    MILLISECONDS_PER_YEAR,
    SECONDS_PER_MINUTE,
    SECONDS_PER_HOUR,
    SECONDS_PER_DAY,
    SECONDS_PER_WEEK,
    SECONDS_PER_MOUNTH,
    SECONDS_PER_YEAR,
})
