const MILLISECONDS_PER_SECOND = 1000;
const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * 60;
const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_MINUTES * 60;
const MILLISECONDS_PER_DAY = MILLISECONDS_PER_HOUR * 24;
const MILLISECONDS_PER_WEEK = MILLISECONDS_PER_DAY * 7;
const MILLISECONDS_PER_MOUNTH = MILLISECONDS_PER_WEEK * 30;
const MILLISECONDS_PER_YEAR = MILLISECONDS_PER_MOUNTH * 12;

export default Object.freeze({
    MILLISECONDS_PER_SECOND,
    MILLISECONDS_PER_MINUTE,
    MILLISECONDS_PER_HOUR,
    MILLISECONDS_PER_DAY,
    MILLISECONDS_PER_WEEK,
    MILLISECONDS_PER_MOUNTH,
    MILLISECONDS_PER_YEAR,
})
